[project]
name = "jibril"
version = "0.1.0"
description = "A forgotten image organizer"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "loguru>=0.7.3",
    "pydantic-settings>=2.12.0",
    "typed-settings[attrs]>=25.3.0",
    "typer>=0.20.0",
]
